/**
 * Applying migrations, **per database**: each (server, account) pair has its
 * own.
 *
 * `migrateDatabase` memoises by file name and by promise: two callers in the
 * same tick share the same run instead of racing two `migrate()` on the same
 * database. The body lives in an async function: even a **synchronous** throw
 * (`openDatabaseSync` on a corrupt file) becomes a rejection, which the
 * caller catches instead of crashing.
 */

import { migrate } from 'drizzle-orm/expo-sqlite/migrator';

import { openDatabase } from './client.ts';
// Generated by `npm run db:generate`. Resolved thanks to `babel-plugin-inline-import`
// and the `sql` extension added to Metro's `sourceExts`.
import migrations from './migrations/migrations.js';
import { databaseFileName } from './fileName.ts';

/**
 * The server offered by default on the login screen, and the one whose
 * database backs the debug screen outside a session. Step 5.3 (multi-server)
 * will make the "active server" the only reference.
 *
 * In release, the project's TARGET server; the local Docker only makes sense
 * in dev. The `typeof` guard: this module is also loaded under Node (tests),
 * where `__DEV__` does not exist.
 */
export const DEFAULT_SERVER =
  typeof __DEV__ !== 'undefined' && __DEV__ ? 'http://localhost:3000' : 'https://chat.barrut.me';

const inProgress = new Map<string, Promise<void>>();

export function migrateDatabase(baseUrl: string, userId?: string): Promise<void> {
  const name = databaseFileName(baseUrl, userId);
  const existing = inProgress.get(name);
  if (existing !== undefined) return existing;

  const promise = (async () => {
    await migrate(openDatabase(baseUrl, userId).base, migrations);
  })();
  inProgress.set(name, promise);
  // A failure must not stay memoised: the next call retries.
  promise.catch(() => inProgress.delete(name));
  return promise;
}
