import assert from 'node:assert/strict';
import { readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { describe, test } from 'node:test';
import { fileURLToPath } from 'node:url';

import { getTableConfig } from 'drizzle-orm/sqlite-core';

import {
  cursors, drafts, customEmojis, messages, outbox, rooms, subscriptions, uploads, users,
  nativeSyncState, nativePositions, nativeStarStates, nativeRoomCreations, nativeMessageCommands, nativeRoomOperations, nativeProfileOperations, nativeUploadIntents, nativeRoomAccess, nativeReadStates, nativeReadIntents, nativeThreadStates, nativeThreadReadIntents, nativeFavoriteIntents, nativeQuoteReferences, nativeQuoteSources, nativeOutboxQuotes, nativeEmojiCatalog,
} from './schema.ts';

/**
 * Migrations are generated by `drizzle-kit`. Generated does not mean valid:
 * we really apply them, on an in-memory SQLite.
 * `db/migrations/*.sql` uses `--> statement-breakpoint` as separator.
 */
const FOLDER = join(dirname(fileURLToPath(import.meta.url)), 'migrations');

function migratedDb(): DatabaseSync {
  const db = new DatabaseSync(':memory:');
  const files = readdirSync(FOLDER)
    .filter((f) => f.endsWith('.sql'))
    .sort();
  assert.ok(files.length > 0, 'no migration generated');
  for (const file of files) {
    for (const query of readFileSync(join(FOLDER, file), 'utf8').split(
      '--> statement-breakpoint',
    )) {
      const sql = query.trim();
      if (sql !== '') db.exec(sql);
    }
  }
  return db;
}

function tables(db: DatabaseSync): string[] {
  return db
    .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")
    .all()
    .map((l) => String((l as { name: unknown }).name))
    .sort();
}

/** Applies the migrations whose numeric index is < `before`, in order. */
function migratedDbBefore(before: number): DatabaseSync {
  const db = new DatabaseSync(':memory:');
  const files = readdirSync(FOLDER)
    .filter((f) => f.endsWith('.sql'))
    .sort();
  for (const file of files) {
    if (parseInt(file.slice(0, 4), 10) >= before) continue;
    for (const query of readFileSync(join(FOLDER, file), 'utf8').split(
      '--> statement-breakpoint',
    )) {
      const sql = query.trim();
      if (sql !== '') db.exec(sql);
    }
  }
  return db;
}

/** Applies the statements of ONE migration file (by its index). */
function applyMigration(db: DatabaseSync, index: number): void {
  const file = readdirSync(FOLDER).find((f) => parseInt(f.slice(0, 4), 10) === index);
  assert.ok(file !== undefined, `migration ${index} missing`);
  for (const query of readFileSync(join(FOLDER, file), 'utf8').split('--> statement-breakpoint')) {
    const sql = query.trim();
    if (sql !== '') db.exec(sql);
  }
}

describe('identities backfill (0009)', () => {
  test('seeds users from EXISTING messages: most recent username per uid', () => {
    // A database from BEFORE the identities table, with history already there.
    const db = migratedDbBefore(9);
    const ins =
      'INSERT INTO messages (id, rid, horodatage, auteur_id, auteur_nom, mis_a_jour_le) VALUES (?, ?, ?, ?, ?, ?)';
    // u1: old username (100) then renamed (200). u2: a single message. u3:
    // encrypted message without auteur_nom -> must NOT create an identity.
    db.prepare(ins).run('m1', 'r1', 1, 'u1', 'alice', 100);
    db.prepare(ins).run('m2', 'r1', 2, 'u1', 'alice-new', 200);
    db.prepare(ins).run('m3', 'r1', 3, 'u2', 'bob', 150);
    db.prepare(ins).run('m4', 'r1', 4, 'u3', null, 300);

    applyMigration(db, 9);

    const rows = db
      .prepare('SELECT uid, username, mis_a_jour_le FROM utilisateurs ORDER BY uid')
      .all()
      .map((l) => ({ ...(l as Record<string, unknown>) }));
    assert.deepEqual(rows, [
      { uid: 'u1', username: 'alice-new', mis_a_jour_le: 200 },
      { uid: 'u2', username: 'bob', mis_a_jour_le: 150 },
    ]);
    db.close();
  });
});

describe('migrations', () => {
  test('the generated SQL applies on a blank database', () => {
    const db = migratedDb();
    assert.deepEqual(tables(db), [
      'cursors',
      'custom_emojis',
      'drafts',
      'messages',
      'native_commands',
      'native_emoji_catalog',
      'native_favorite_intents',
      'native_outbox_quotes',
      'native_positions',
      'native_profile_operations',
      'native_quote_references',
      'native_quote_sources',
      'native_read_intents',
      'native_read_states',
      'native_room_access',
      'native_room_creations',
      'native_room_operations',
      'native_star_states',
      'native_sync_state',
      'native_thread_read_intents',
      'native_thread_states',
      'native_upload_intents',
      'outbox',
      'rooms',
      'subscriptions',
      'uploads',
      'users',
    ]);
    db.close();
  });

  test('the indexes carrying the hot queries exist', () => {
    const db = migratedDb();
    const index = db
      .prepare("SELECT name FROM sqlite_master WHERE type='index' AND name LIKE 'idx_%'")
      .all()
      .map((l) => String((l as { name: unknown }).name))
      .sort();
    assert.deepEqual(index, [
      'idx_messages_room_ts',
      'idx_messages_thread',
      'idx_native_command_message',
      'idx_native_favorite_operation',
      'idx_native_positions_room',
      'idx_native_profile_operation_slot',
      'idx_native_quote_origins',
      'idx_native_quote_source_rooms',
      'idx_native_room_creation_form',
      'idx_native_room_operation_room',
      'idx_native_star_room',
      'idx_outbox_status',
      'idx_rooms_activity',
      'idx_uploads_status',
    ]);
    db.close();
  });

  test('the room screen\'s query does use its index', () => {
    const db = migratedDb();
    // `WHERE rid = ? ORDER BY ts DESC` is THE query of step 4.2: if it
    // goes through a full scan, the list will crawl from 10,000 messages on.
    const plan = db
      .prepare('EXPLAIN QUERY PLAN SELECT * FROM messages WHERE rid = ? ORDER BY ts DESC')
      .all()
      .map((l) => String((l as { detail: unknown }).detail))
      .join(' ');
    assert.match(plan, /USING INDEX idx_messages_room_ts/);
    assert.doesNotMatch(plan, /SCAN messages/);
    db.close();
  });

  test('two messages in the same millisecond are ordered deterministically', () => {
    // Without a secondary key, SQLite returns ties in INSERTION order (rowid),
    // hence BACKWARDS after a history pagination (inserted from newest to
    // oldest). We break ties by `id`: the order must be the SAME whatever the
    // insertion order. It is the room screen's query.
    const QUERY =
      'SELECT id FROM messages WHERE rid = ? ORDER BY ts DESC, id DESC LIMIT 50';
    const insert = (db: DatabaseSync, ids: string[]) => {
      const stmt = db.prepare(
        'INSERT INTO messages (id, rid, ts, author_id) VALUES (?, ?, ?, ?)',
      );
      for (const id of ids) stmt.run(id, 'rid-1', 1000, 'u1');
    };
    const read = (db: DatabaseSync) =>
      (db.prepare(QUERY).all('rid-1') as { id: string }[]).map((r) => r.id);

    const growing = migratedDb();
    insert(growing, ['a', 'b', 'c']);
    const descending = migratedDb();
    insert(descending, ['c', 'b', 'a']); // reverse insertion order (pagination)

    assert.deepEqual(read(growing), ['c', 'b', 'a']);
    // The key invariant: reverse insertion -> SAME displayed order (before the
    // fix, this returned ['a', 'b', 'c']).
    assert.deepEqual(read(descending), read(growing));
    growing.close();
    descending.close();
  });

  test('`id` deduplicates messages: a second insert is refused', () => {
    const db = migratedDb();
    const insert = db.prepare(
      'INSERT INTO messages (id, rid, ts, author_id) VALUES (?, ?, ?, ?)',
    );
    insert.run('msg-1', 'rid-1', 1000, 'u1');
    assert.throws(() => insert.run('msg-1', 'rid-1', 1000, 'u1'), /UNIQUE/);
    db.close();
  });

  test('`cursors` does have a composite key (scope, stream)', () => {
    const db = migratedDb();
    const insert = db.prepare(
      'INSERT INTO cursors (scope, stream, updated_since) VALUES (?, ?, ?)',
    );
    insert.run('rid-1', 'messages', 1);
    insert.run('rid-1', 'subscriptions', 1); // same scope, other stream: accepted
    insert.run('*', 'messages', 1); // global cursor
    assert.throws(() => insert.run('rid-1', 'messages', 2), /UNIQUE/);
    db.close();
  });

  test('default values avoid unexpected null columns', () => {
    const db = migratedDb();
    db.prepare('INSERT INTO rooms (rid, type) VALUES (?, ?)').run('r1', 'c');
    const room = db.prepare('SELECT * FROM rooms WHERE rid = ?').get('r1') as Record<
      string,
      unknown
    >;
    assert.equal(room.encrypted, 0);
    assert.equal(room.read_only, 0);
    assert.equal(room.updated_at, 0);

    db.prepare('INSERT INTO outbox (id, rid, text, created_at) VALUES (?, ?, ?, ?)').run(
      's1',
      'r1',
      'hey',
      42,
    );
    const outbox = db.prepare('SELECT * FROM outbox WHERE id = ?').get('s1') as Record<
      string,
      unknown
    >;
    assert.equal(outbox.status, 'pending');
    assert.equal(outbox.attempts, 0);
    db.close();
  });
});

/**
 * `file_id` lands on a database ALREADY running on the phone, with upload
 * rows in it. Drizzle's migrator applies migrations in a single transaction,
 * with ROLLBACK on error: a failing `ALTER TABLE` does not break the
 * database, it blocks startup in the `error` phase. This test therefore
 * stands for the real launch on the Pixel.
 */
describe('adding file_id to the upload queue (0013)', () => {
  test('a database from BEFORE, with rows, gains the column without losing anything', () => {
    const db = migratedDbBefore(13);

    db.prepare(
      'INSERT INTO televersements (id, rid, uri, nom, type, legende, cree_le) VALUES (?, ?, ?, ?, ?, ?, ?)',
    ).run('t1', 'r1', 'file:///old.png', 'old.png', 'image/png', 'my caption', 1000);

    applyMigration(db, 13);

    const l = db.prepare('SELECT * FROM televersements WHERE id = ?').get('t1') as Record<
      string,
      unknown
    >;
    assert.equal(l.uri, 'file:///old.png', 'the row from before survives intact');
    assert.equal(l.legende, 'my caption');
    assert.equal(l.statut, 'en-attente');
    assert.equal(l.file_id, null, 'the column exists and is NULL on the history');

    // And it is writable: that is the whole point of the migration.
    db.prepare('UPDATE televersements SET file_id = ? WHERE id = ?').run('abc123', 't1');
    const after = db.prepare('SELECT file_id FROM televersements WHERE id = ?').get('t1') as Record<
      string,
      unknown
    >;
    assert.equal(after.file_id, 'abc123');
    db.close();
  });

  test('the migration journal and bundle are consistent, otherwise the app does not start', () => {
    // `readMigrationFiles` throws "Missing migration: <tag>" if a journal entry
    // has no `m00NN` key in the generated migrations.js. The test catches a
    // forgotten `npm run db:generate`, which otherwise only shows at real
    // launch.
    const log = JSON.parse(readFileSync(join(FOLDER, 'meta', '_journal.json'), 'utf8')) as {
      entries: { idx: number; tag: string }[];
    };
    const bundle = readFileSync(join(FOLDER, 'migrations.js'), 'utf8');
    const files = readdirSync(FOLDER).filter((f) => f.endsWith('.sql'));
    assert.equal(log.entries.length, files.length, 'one .sql per journal entry');
    for (const e of log.entries) {
      const key = `m${String(e.idx).padStart(4, '0')}`;
      assert.ok(bundle.includes(`${key} from './${e.tag}.sql'`), `${key} missing from the bundle`);
      assert.ok(files.includes(`${e.tag}.sql`), `${e.tag}.sql missing from the folder`);
    }
  });
});

describe('subscription roles (0015)', () => {
  test('adds the column and forgets the subscriptions cursor, not the others', () => {
    const db = migratedDbBefore(15);
    const ins = 'INSERT INTO etat_synchro (portee, flux, mis_a_jour_depuis) VALUES (?, ?, ?)';
    db.prepare(ins).run('*', 'abonnements', 100);
    db.prepare(ins).run('*', 'salons', 100);
    db.prepare(ins).run('r1', 'messages', 100);

    applyMigration(db, 15);

    const cursors = db
      .prepare('SELECT portee, flux FROM etat_synchro ORDER BY portee, flux')
      .all()
      .map((l) => ({ ...(l as Record<string, unknown>) }));
    assert.deepEqual(cursors, [
      { portee: '*', flux: 'salons' },
      { portee: 'r1', flux: 'messages' },
    ]);
    db.prepare("INSERT INTO abonnements (rid, roles) VALUES ('r1', '[\"owner\"]')").run();
    db.close();
  });
});

describe('English names (0016)', () => {
  test('a database from BEFORE keeps every row, under the new names and values', () => {
    const db = migratedDbBefore(16);
    db.exec(`
      INSERT INTO salons (rid, type, nom, nom_affiche, chiffre, horodatage_dernier_message, avatar_etag, mis_a_jour_le)
        VALUES ('r1', 'c', 'general', 'General', 1, 50, 'sans-photo', 7);
      INSERT INTO abonnements (rid, non_lus, favori, lu_jusqu_a) VALUES ('r1', 3, 1, 40);
      INSERT INTO messages (id, rid, texte, horodatage, auteur_id, fil_id, epingle, mis_a_jour_le)
        VALUES ('m1', 'r1', 'hello', 10, 'u1', 'm0', 1, 11);
      INSERT INTO sortie (id, rid, texte, statut, tentatives, cree_le) VALUES ('s1', 'r1', 'a', 'en-attente', 0, 1);
      INSERT INTO sortie (id, rid, texte, statut, tentatives, derniere_erreur, cree_le)
        VALUES ('s2', 'r1', 'b', 'echec', 2, '400', 2);
      INSERT INTO televersements (id, rid, uri, nom, type, legende, statut, file_id, cree_le)
        VALUES ('t1', 'r1', 'file:///a.png', 'a.png', 'image/png', 'cap', 'envoi', 'f1', 3);
      INSERT INTO televersements (id, rid, uri, nom, type, statut, cree_le)
        VALUES ('t2', 'r1', 'file:///b.png', 'b.png', 'image/png', 'en-attente', 4),
          ('t3', 'r1', 'file:///c.png', 'c.png', 'image/png', 'echec', 5);
      INSERT INTO brouillons (cle, texte, mis_a_jour_le) VALUES ('r1', 'draft', 4);
      INSERT INTO emojis_custom (nom, extension) VALUES ('parrot', 'gif');
      INSERT INTO utilisateurs (uid, username, avatar_etag) VALUES ('u1', 'alice', 'sans-photo');
      INSERT INTO etat_synchro (portee, flux, mis_a_jour_depuis)
        VALUES ('*', 'salons', 1), ('*', 'abonnements', 2), ('r1', 'messages-supprimes', 3), ('r1', 'messages', 4);
    `);

    applyMigration(db, 16);

    const all = (sql: string) =>
      db
        .prepare(sql)
        .all()
        .map((l) => ({ ...(l as Record<string, unknown>) }));
    assert.deepEqual(
      all('SELECT rid, name, display_name, encrypted, last_message_ts, avatar_etag, updated_at FROM rooms'),
      [
        {
          rid: 'r1',
          name: 'general',
          display_name: 'General',
          encrypted: 1,
          last_message_ts: 50,
          avatar_etag: 'none',
          updated_at: 7,
        },
      ],
    );
    assert.deepEqual(all('SELECT unread, favorite, last_seen FROM subscriptions'), [
      { unread: 3, favorite: 1, last_seen: 40 },
    ]);
    assert.deepEqual(all('SELECT text, ts, author_id, thread_id, pinned, updated_at FROM messages'), [
      { text: 'hello', ts: 10, author_id: 'u1', thread_id: 'm0', pinned: 1, updated_at: 11 },
    ]);
    assert.deepEqual(all('SELECT id, text, status, attempts, last_error, created_at FROM outbox ORDER BY id'), [
      { id: 's1', text: 'a', status: 'pending', attempts: 0, last_error: null, created_at: 1 },
      { id: 's2', text: 'b', status: 'failed', attempts: 2, last_error: '400', created_at: 2 },
    ]);
    assert.deepEqual(all('SELECT name, caption, status, file_id, created_at FROM uploads ORDER BY created_at'), [
      { name: 'a.png', caption: 'cap', status: 'sending', file_id: 'f1', created_at: 3 },
      { name: 'b.png', caption: null, status: 'pending', file_id: null, created_at: 4 },
      { name: 'c.png', caption: null, status: 'failed', file_id: null, created_at: 5 },
    ]);
    assert.deepEqual(all('SELECT key, text, updated_at FROM drafts'), [
      { key: 'r1', text: 'draft', updated_at: 4 },
    ]);
    assert.deepEqual(all('SELECT name FROM custom_emojis'), [{ name: 'parrot' }]);
    assert.deepEqual(all('SELECT avatar_etag FROM users'), [{ avatar_etag: 'none' }]);
    assert.deepEqual(all('SELECT scope, stream, updated_since FROM cursors ORDER BY updated_since'), [
      { scope: '*', stream: 'rooms', updated_since: 1 },
      { scope: '*', stream: 'subscriptions', updated_since: 2 },
      { scope: 'r1', stream: 'messages-deleted', updated_since: 3 },
      { scope: 'r1', stream: 'messages', updated_since: 4 },
    ]);
    db.prepare("INSERT INTO outbox (id, rid, text, created_at) VALUES ('s3', 'r1', 'c', 5)").run();
    assert.deepEqual(all("SELECT status FROM outbox WHERE id = 's3'"), [{ status: 'pending' }]);
    // Every later migration, so the tables match the current schema.
    for (const later of [17, 18, 19]) applyMigration(db, later);
    assert.deepEqual(tables(db), tables(migratedDb()));
    db.close();
  });

  test('the migrated database has exactly the columns of schema.ts', () => {
    const db = migratedDb();
    for (const table of [
      rooms, subscriptions, messages, outbox, uploads, drafts, customEmojis, users, cursors,
      nativeSyncState, nativePositions, nativeStarStates, nativeRoomCreations, nativeMessageCommands, nativeRoomOperations, nativeProfileOperations, nativeUploadIntents, nativeRoomAccess, nativeReadStates, nativeReadIntents, nativeThreadStates, nativeThreadReadIntents, nativeFavoriteIntents, nativeQuoteReferences, nativeQuoteSources, nativeOutboxQuotes, nativeEmojiCatalog,
    ]) {
      const config = getTableConfig(table);
      const actual = db
        .prepare(`PRAGMA table_info(${config.name})`)
        .all()
        .map((l) => {
          const c = l as { name: string; notnull: number };
          return `${c.name}:${c.notnull === 1}`;
        })
        .sort();
      const expected = config.columns.map((c) => `${c.name}:${c.notNull}`).sort();
      assert.deepEqual(actual, expected, config.name);
    }
    db.close();
  });
});

describe('native provider tables (0017)', () => {
  test('re-applying it on a pilot database that already has the tables keeps every row', () => {
    // Pilot builds of the feature branch created the same tables through
    // their own migrations; this one must then be a no-op, not a failure.
    const db = migratedDb();
    try {
      db.exec("INSERT INTO native_commands(id,rid,message_id,kind,expected_revision,text) VALUES('old-operation','room','message','edit','9007199254740993','Saved draft')");
      db.prepare('INSERT INTO native_positions(id,rid,position,revision) VALUES(?,?,?,?)').run('old-message', 'origin', '9007199254740993', '9007199254740993');
      applyMigration(db, 17);
      const row = db.prepare('SELECT id,expected_revision,text,state,quotes FROM native_commands').get()!;
      assert.equal(row.id, 'old-operation');
      assert.equal(row.expected_revision, '9007199254740993');
      assert.equal(row.text, 'Saved draft');
      assert.equal(row.state, 'pending');
      assert.equal(row.quotes, null);
      const position = db.prepare('SELECT position FROM native_positions WHERE id=?').get('old-message') as { position: string };
      assert.equal(position.position, '9007199254740993');
    } finally {
      db.close();
    }
  });
});
