import assert from 'node:assert/strict';
import { readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { describe, test } from 'node:test';
import { fileURLToPath } from 'node:url';

/**
 * Migrations are generated by `drizzle-kit`. Generated does not mean valid:
 * we really apply them, on an in-memory SQLite.
 * `db/migrations/*.sql` uses `--> statement-breakpoint` as separator.
 */
const FOLDER = join(dirname(fileURLToPath(import.meta.url)), 'migrations');

function migratedDb(): DatabaseSync {
  const db = new DatabaseSync(':memory:');
  const files = readdirSync(FOLDER)
    .filter((f) => f.endsWith('.sql'))
    .sort();
  assert.ok(files.length > 0, 'no migration generated');
  for (const file of files) {
    for (const query of readFileSync(join(FOLDER, file), 'utf8').split(
      '--> statement-breakpoint',
    )) {
      const sql = query.trim();
      if (sql !== '') db.exec(sql);
    }
  }
  return db;
}

function tables(db: DatabaseSync): string[] {
  return db
    .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")
    .all()
    .map((l) => String((l as { name: unknown }).name))
    .sort();
}

/** Applies the migrations whose numeric index is < `before`, in order. */
function migratedDbBefore(before: number): DatabaseSync {
  const db = new DatabaseSync(':memory:');
  const files = readdirSync(FOLDER)
    .filter((f) => f.endsWith('.sql'))
    .sort();
  for (const file of files) {
    if (parseInt(file.slice(0, 4), 10) >= before) continue;
    for (const query of readFileSync(join(FOLDER, file), 'utf8').split(
      '--> statement-breakpoint',
    )) {
      const sql = query.trim();
      if (sql !== '') db.exec(sql);
    }
  }
  return db;
}

/** Applies the statements of ONE migration file (by its index). */
function applyMigration(db: DatabaseSync, index: number): void {
  const file = readdirSync(FOLDER).find((f) => parseInt(f.slice(0, 4), 10) === index);
  assert.ok(file !== undefined, `migration ${index} absente`);
  for (const query of readFileSync(join(FOLDER, file), 'utf8').split('--> statement-breakpoint')) {
    const sql = query.trim();
    if (sql !== '') db.exec(sql);
  }
}

describe('identities backfill (0009)', () => {
  test('seeds users from EXISTING messages: most recent username per uid', () => {
    // A database from BEFORE the identities table, with history already there.
    const db = migratedDbBefore(9);
    const ins =
      'INSERT INTO messages (id, rid, horodatage, auteur_id, auteur_nom, mis_a_jour_le) VALUES (?, ?, ?, ?, ?, ?)';
    // u1: old username (100) then renamed (200). u2: a single message. u3:
    // encrypted message without auteur_nom -> must NOT create an identity.
    db.prepare(ins).run('m1', 'r1', 1, 'u1', 'alice', 100);
    db.prepare(ins).run('m2', 'r1', 2, 'u1', 'alice-neuve', 200);
    db.prepare(ins).run('m3', 'r1', 3, 'u2', 'bob', 150);
    db.prepare(ins).run('m4', 'r1', 4, 'u3', null, 300);

    applyMigration(db, 9);

    const rows = db
      .prepare('SELECT uid, username, mis_a_jour_le FROM utilisateurs ORDER BY uid')
      .all()
      .map((l) => ({ ...(l as Record<string, unknown>) }));
    assert.deepEqual(rows, [
      { uid: 'u1', username: 'alice-neuve', mis_a_jour_le: 200 },
      { uid: 'u2', username: 'bob', mis_a_jour_le: 150 },
    ]);
    db.close();
  });
});

describe('migrations', () => {
  test('the generated SQL applies on a blank database', () => {
    const db = migratedDb();
    assert.deepEqual(tables(db), [
      'abonnements',
      'brouillons',
      'emojis_custom',
      'etat_synchro',
      'messages',
      'salons',
      'sortie',
      'televersements',
      'utilisateurs',
    ]);
    db.close();
  });

  test('the indexes carrying the hot queries exist', () => {
    const db = migratedDb();
    const index = db
      .prepare("SELECT name FROM sqlite_master WHERE type='index' AND name LIKE 'idx_%'")
      .all()
      .map((l) => String((l as { name: unknown }).name))
      .sort();
    assert.deepEqual(index, [
      'idx_messages_fil',
      'idx_messages_salon_date',
      'idx_salons_activite',
      'idx_sortie_statut',
      'idx_televersements_statut',
    ]);
    db.close();
  });

  test('the room screen\'s query does use its index', () => {
    const db = migratedDb();
    // `WHERE rid = ? ORDER BY horodatage DESC` is THE query of step 4.2: if it
    // goes through a full scan, the list will crawl from 10,000 messages on.
    const plan = db
      .prepare('EXPLAIN QUERY PLAN SELECT * FROM messages WHERE rid = ? ORDER BY horodatage DESC')
      .all()
      .map((l) => String((l as { detail: unknown }).detail))
      .join(' ');
    assert.match(plan, /USING INDEX idx_messages_salon_date/);
    assert.doesNotMatch(plan, /SCAN messages/);
    db.close();
  });

  test('two messages in the same millisecond are ordered deterministically', () => {
    // Without a secondary key, SQLite returns ties in INSERTION order (rowid),
    // hence BACKWARDS after a history pagination (inserted from newest to
    // oldest). We break ties by `id`: the order must be the SAME whatever the
    // insertion order. It is the room screen's query.
    const QUERY =
      'SELECT id FROM messages WHERE rid = ? ORDER BY horodatage DESC, id DESC LIMIT 50';
    const insert = (db: DatabaseSync, ids: string[]) => {
      const stmt = db.prepare(
        'INSERT INTO messages (id, rid, horodatage, auteur_id) VALUES (?, ?, ?, ?)',
      );
      for (const id of ids) stmt.run(id, 'rid-1', 1000, 'u1');
    };
    const read = (db: DatabaseSync) =>
      (db.prepare(QUERY).all('rid-1') as { id: string }[]).map((r) => r.id);

    const growing = migratedDb();
    insert(growing, ['a', 'b', 'c']);
    const descending = migratedDb();
    insert(descending, ['c', 'b', 'a']); // ordre d'insertion inverse (pagination)

    assert.deepEqual(read(growing), ['c', 'b', 'a']);
    // The key invariant: reverse insertion -> SAME displayed order (before the
    // fix, this returned ['a', 'b', 'c']).
    assert.deepEqual(read(descending), read(growing));
    growing.close();
    descending.close();
  });

  test('`id` deduplicates messages: a second insert is refused', () => {
    const db = migratedDb();
    const insert = db.prepare(
      'INSERT INTO messages (id, rid, horodatage, auteur_id) VALUES (?, ?, ?, ?)',
    );
    insert.run('msg-1', 'rid-1', 1000, 'u1');
    assert.throws(() => insert.run('msg-1', 'rid-1', 1000, 'u1'), /UNIQUE/);
    db.close();
  });

  test('`cursors` does have a composite key (scope, stream)', () => {
    const db = migratedDb();
    const insert = db.prepare(
      'INSERT INTO etat_synchro (portee, flux, mis_a_jour_depuis) VALUES (?, ?, ?)',
    );
    insert.run('rid-1', 'messages', 1);
    insert.run('rid-1', 'abonnements', 1); // same scope, other stream: accepted
    insert.run('*', 'messages', 1); // curseur global
    assert.throws(() => insert.run('rid-1', 'messages', 2), /UNIQUE/);
    db.close();
  });

  test('default values avoid unexpected null columns', () => {
    const db = migratedDb();
    db.prepare('INSERT INTO salons (rid, type) VALUES (?, ?)').run('r1', 'c');
    const room = db.prepare('SELECT * FROM salons WHERE rid = ?').get('r1') as Record<
      string,
      unknown
    >;
    assert.equal(room.chiffre, 0);
    assert.equal(room.lecture_seule, 0);
    assert.equal(room.mis_a_jour_le, 0);

    db.prepare('INSERT INTO sortie (id, rid, texte, cree_le) VALUES (?, ?, ?, ?)').run(
      's1',
      'r1',
      'coucou',
      42,
    );
    const outbox = db.prepare('SELECT * FROM sortie WHERE id = ?').get('s1') as Record<
      string,
      unknown
    >;
    assert.equal(outbox.statut, 'en-attente');
    assert.equal(outbox.tentatives, 0);
    db.close();
  });
});

/**
 * `file_id` lands on a database ALREADY running on the phone, with upload
 * rows in it. Drizzle's migrator applies migrations in a single transaction,
 * with ROLLBACK on error: a failing `ALTER TABLE` does not break the
 * database, it blocks startup in the `error` phase. This test therefore
 * stands for the real launch on the Pixel.
 */
describe('adding file_id to the upload queue (0013)', () => {
  test('a database from BEFORE, with rows, gains the column without losing anything', () => {
    const db = migratedDbBefore(13);

    db.prepare(
      'INSERT INTO televersements (id, rid, uri, nom, type, legende, cree_le) VALUES (?, ?, ?, ?, ?, ?, ?)',
    ).run('t1', 'r1', 'file:///vieux.png', 'vieux.png', 'image/png', 'ma légende', 1000);

    applyMigration(db, 13);

    const l = db.prepare('SELECT * FROM televersements WHERE id = ?').get('t1') as Record<
      string,
      unknown
    >;
    assert.equal(l.uri, 'file:///vieux.png', 'the row from before survives intact');
    assert.equal(l.legende, 'ma légende');
    assert.equal(l.statut, 'en-attente');
    assert.equal(l.file_id, null, 'the column exists and is NULL on the history');

    // And it is writable: that is the whole point of the migration.
    db.prepare('UPDATE televersements SET file_id = ? WHERE id = ?').run('abc123', 't1');
    const after = db.prepare('SELECT file_id FROM televersements WHERE id = ?').get('t1') as Record<
      string,
      unknown
    >;
    assert.equal(after.file_id, 'abc123');
    db.close();
  });

  test('the migration journal and bundle are consistent, otherwise the app does not start', () => {
    // `readMigrationFiles` throws "Missing migration: <tag>" if a journal entry
    // has no `m00NN` key in the generated migrations.js. The test catches a
    // forgotten `npm run db:generate`, which otherwise only shows at real
    // launch.
    const log = JSON.parse(readFileSync(join(FOLDER, 'meta', '_journal.json'), 'utf8')) as {
      entries: { idx: number; tag: string }[];
    };
    const bundle = readFileSync(join(FOLDER, 'migrations.js'), 'utf8');
    const files = readdirSync(FOLDER).filter((f) => f.endsWith('.sql'));
    assert.equal(log.entries.length, files.length, 'one .sql per journal entry');
    for (const e of log.entries) {
      const key = `m${String(e.idx).padStart(4, '0')}`;
      assert.ok(bundle.includes(`${key} from './${e.tag}.sql'`), `${key} missing from the bundle`);
      assert.ok(files.includes(`${e.tag}.sql`), `${e.tag}.sql missing from the folder`);
    }
  });
});

describe('subscription roles (0015)', () => {
  test('adds the column and forgets the subscriptions cursor, not the others', () => {
    const db = migratedDbBefore(15);
    const ins = 'INSERT INTO etat_synchro (portee, flux, mis_a_jour_depuis) VALUES (?, ?, ?)';
    db.prepare(ins).run('*', 'abonnements', 100);
    db.prepare(ins).run('*', 'salons', 100);
    db.prepare(ins).run('r1', 'messages', 100);

    applyMigration(db, 15);

    const cursors = db
      .prepare('SELECT portee, flux FROM etat_synchro ORDER BY portee, flux')
      .all()
      .map((l) => ({ ...(l as Record<string, unknown>) }));
    assert.deepEqual(cursors, [
      { portee: '*', flux: 'salons' },
      { portee: 'r1', flux: 'messages' },
    ]);
    db.prepare("INSERT INTO abonnements (rid, roles) VALUES ('r1', '[\"owner\"]')").run();
    db.close();
  });
});
