// The native pilot's transport orchestration is platform independent. Generate
// the browser modules from those sources, never a separately maintained fork.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { format } from "prettier";
const source = "../mobile/providers/rocketvibe/";
const destination = "src/crypto/shared/";
mkdirSync(destination, { recursive: true });
const protocol = readFileSync(source + "protocol.generated.ts", "utf8");
const schema = protocol.slice(protocol.indexOf("export const nativeSchema"));
if (!schema) throw Error("Native schema changed");
writeFileSync(
  "src/crypto/schema.generated.ts",
  await format("// Generated native protocol runtime schema.\n" + schema, {
    parser: "typescript",
    filepath: "src/crypto/schema.generated.ts",
  }),
);
const names = [
  "cryptoStorage",
  "cryptoIdentity",
  "cryptoPeers",
  "cryptoGroups",
  "cryptoConversations",
  "cryptoQuotes",
  "cryptoWithdrawals",
  "cryptoRecovery",
  "cryptoHistory",
  "cryptoHistoryBackup",
  "cryptoStorageKey",
  "validation",
  "emojis",
  "emoji-aliases.generated",
];
for (const name of names) {
  let text = readFileSync(source + name + ".ts", "utf8")
    .replaceAll("../../modules/crypto-native/index.ts", "../bridge-types.ts")
    .replaceAll("./protocol.generated.ts", "../../protocol.ts")
    .replaceAll("./transport.ts", "../transport.ts")
    .replaceAll("./quotes.ts", "../quote-types.ts")
    .replaceAll("./fileDescriptors.ts", "../file-descriptors.ts");
  writeFileSync(
    destination + name + ".ts",
    await format(
      "// Generated by scripts/sync-crypto.mjs from " +
        source +
        name +
        ".ts.\n" +
        text,
      { parser: "typescript", filepath: destination + name + ".ts" },
    ),
  );
}
const types = readFileSync("../mobile/modules/crypto-native/index.ts", "utf8")
  .split("\n")
  .slice(1)
  .join("\n")
  .split("export const CryptoNative =")[0];
writeFileSync(
  "src/crypto/bridge-types.ts",
  await format(
    "// Generated public bridge types. No Expo runtime in this module.\n" +
      types,
    { parser: "typescript", filepath: "src/crypto/bridge-types.ts" },
  ),
);
