// One wire contract for all clients; regenerated by scripts/generate-native-protocol.mjs.
export type * from "../../mobile/providers/rocketvibe/protocol.generated";
export { nativeSchema } from "./crypto/schema.generated";
