/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_bridge_free: (a: number, b: number) => void;
export const __wbg_sealedfile_free: (a: number, b: number) => void;
export const bridge_close: (a: number) => void;
export const bridge_invoke: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const bridge_new: (a: number, b: number) => [number, number, number];
export const bridge_restore: (a: number, b: number, c: number) => [number, number];
export const bridge_snapshot: (a: number) => [number, number, number, number];
export const open_file: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number];
export const seal_file: (a: number, b: number, c: any) => [number, number, number];
export const sealedfile_metadata: (a: number) => [number, number];
export const sealedfile_object: (a: number) => [number, number];
export const rust_sqlite_wasm_abort: () => void;
export const rust_sqlite_wasm_assert_fail: (a: number, b: number, c: number, d: number) => void;
export const rust_sqlite_wasm_calloc: (a: number, b: number) => number;
export const rust_sqlite_wasm_malloc: (a: number) => number;
export const rust_sqlite_wasm_free: (a: number) => void;
export const rust_sqlite_wasm_getentropy: (a: number, b: number) => number;
export const rust_sqlite_wasm_localtime: (a: number) => number;
export const rust_sqlite_wasm_realloc: (a: number, b: number) => number;
export const sqlite3_os_end: () => number;
export const sqlite3_os_init: () => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
