//! Shortcode to Unicode, the table Rocket.Chat does NOT send: the server
//! parses `:smile:` into `{type: EMOJI, shortCode: smile}` and stops there.
//! Generated by `scripts/generate-emojis.mjs` from emoji-toolkit.

use std::collections::HashMap;
use std::sync::OnceLock;

const TABLE: &str = include_str!("../data/emojis.tsv");

pub const CATEGORIES: [&str; 8] = ["people", "nature", "food", "activity", "travel", "objects", "symbols", "flags"];

struct Emojis {
    by_code: HashMap<&'static str, String>,
    by_category: HashMap<&'static str, Vec<&'static str>>,
}

fn emojis() -> &'static Emojis {
    static EMOJIS: OnceLock<Emojis> = OnceLock::new();
    EMOJIS.get_or_init(|| {
        let mut by_code = HashMap::new();
        let mut by_category: HashMap<&'static str, Vec<&'static str>> = HashMap::new();
        for line in TABLE.lines() {
            let mut fields = line.split('\t');
            let (Some(code), Some(points), Some(category)) = (fields.next(), fields.next(), fields.next()) else {
                continue;
            };
            let glyph: String =
                points.split('-').filter_map(|p| u32::from_str_radix(p, 16).ok().and_then(char::from_u32)).collect();
            if category != "-" {
                by_category.entry(category).or_default().push(code);
            }
            by_code.insert(code, glyph);
        }
        Emojis { by_code, by_category }
    })
}

/// `smile` (with or without the colons) to its glyph.
pub fn unicode(shortcode: &str) -> Option<&'static str> {
    let code = shortcode.trim_matches(':');
    emojis().by_code.get(code).map(String::as_str)
}

/// `:smile:` in plain text (a room preview) to its glyph; unknown codes stay.
pub fn replace_shortcodes(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(start) = rest.find(':') {
        out.push_str(&rest[..start]);
        let after = &rest[start + 1..];
        let end = after.find(':');
        let candidate = end
            .map(|e| &after[..e])
            .filter(|c| !c.is_empty() && c.chars().all(|ch| ch.is_ascii_alphanumeric() || "_+-".contains(ch)));
        match candidate.and_then(|c| unicode(c).map(|g| (c, g))) {
            Some((code, glyph)) => {
                out.push_str(glyph);
                rest = &after[code.len() + 1..];
            }
            None => {
                out.push(':');
                rest = after;
            }
        }
    }
    out.push_str(rest);
    out
}

/// The picker's base emojis of a category, in JoyPixels order.
pub fn category(name: &str) -> &'static [&'static str] {
    emojis().by_category.get(name).map(Vec::as_slice).unwrap_or(&[])
}

/// Shortcodes starting with `prefix`, shortest first, for `:` completion.
pub fn complete(prefix: &str, limit: usize) -> Vec<(&'static str, &'static str)> {
    let prefix = prefix.trim_start_matches(':').to_lowercase();
    if prefix.is_empty() {
        return Vec::new();
    }
    let mut hits: Vec<(&'static str, &'static str)> = emojis()
        .by_code
        .iter()
        .filter(|(code, _)| code.starts_with(&prefix))
        .map(|(code, glyph)| (*code, glyph.as_str()))
        .collect();
    hits.sort_by(|a, b| a.0.len().cmp(&b.0.len()).then(a.0.cmp(b.0)));
    hits.truncate(limit);
    hits
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolves_shortcodes() {
        assert_eq!(unicode("smile"), Some("😄"));
        assert_eq!(unicode(":+1:"), Some("👍"));
        assert_eq!(unicode("+1_tone3"), Some("👍🏽"));
        assert_eq!(unicode("flag_fr"), Some("🇫🇷"));
        assert_eq!(unicode("not_an_emoji"), None);
    }

    #[test]
    fn picker_categories_hold_base_emojis_only() {
        let people = category("people");
        assert!(people.contains(&"grinning"));
        assert!(!people.iter().any(|c| c.contains("_tone")));
        let total: usize = CATEGORIES.iter().map(|c| category(c).len()).sum();
        assert_eq!(total, 1918);
    }

    #[test]
    fn replaces_known_shortcodes_in_text() {
        assert_eq!(replace_shortcodes(":smile: :heart:"), "😄 ❤️");
        assert_eq!(replace_shortcodes("at 10:30: :party_parrot: ok :+1:"), "at 10:30: :party_parrot: ok 👍");
        assert_eq!(replace_shortcodes("no colons"), "no colons");
        assert_eq!(replace_shortcodes("trailing :"), "trailing :");
    }

    #[test]
    fn completes_by_prefix_shortest_first() {
        let hits = complete(":smi", 3);
        assert_eq!(hits[0].0, "smile");
        assert_eq!(hits.len(), 3);
        assert!(complete("", 5).is_empty());
    }
}
