//! Shortcode to Unicode, the table Rocket.Chat does NOT send: the server
//! parses `:smile:` into `{type: EMOJI, shortCode: smile}` and stops there.
//! Generated by `scripts/generate-emojis.mjs` from emoji-toolkit.

use std::collections::HashMap;
use std::sync::OnceLock;

const TABLE: &str = include_str!("../data/emojis.tsv");

pub const CATEGORIES: [&str; 8] = ["people", "nature", "food", "activity", "travel", "objects", "symbols", "flags"];

struct Emojis {
    by_code: HashMap<&'static str, String>,
    by_category: HashMap<&'static str, Vec<&'static str>>,
    /// Glyph to the first shortcode the table gives it.
    by_glyph: HashMap<String, &'static str>,
}

fn emojis() -> &'static Emojis {
    static EMOJIS: OnceLock<Emojis> = OnceLock::new();
    EMOJIS.get_or_init(|| {
        let mut by_code = HashMap::new();
        let mut by_category: HashMap<&'static str, Vec<&'static str>> = HashMap::new();
        let mut by_glyph: HashMap<String, &'static str> = HashMap::new();
        for line in TABLE.lines() {
            let mut fields = line.split('\t');
            let (Some(code), Some(points), Some(category)) = (fields.next(), fields.next(), fields.next()) else {
                continue;
            };
            let glyph: String =
                points.split('-').filter_map(|p| u32::from_str_radix(p, 16).ok().and_then(char::from_u32)).collect();
            if category != "-" {
                by_category.entry(category).or_default().push(code);
            }
            by_glyph.entry(glyph.clone()).or_insert(code);
            by_code.insert(code, glyph);
        }
        Emojis { by_code, by_category, by_glyph }
    })
}

/// `smile` (with or without the colons) to its glyph.
pub fn unicode(shortcode: &str) -> Option<&'static str> {
    let code = shortcode.trim_matches(':');
    emojis().by_code.get(code).map(String::as_str)
}

/// The shortcode of a glyph, with or without its variation selector.
pub fn shortcode(glyph: &str) -> Option<&'static str> {
    let by_glyph = &emojis().by_glyph;
    by_glyph.get(glyph).or_else(|| by_glyph.get(&glyph.replace('\u{FE0F}', ""))).copied()
}

/// The emoji covering byte `at` of `text`, the longest the table knows, with
/// its shortcode.
pub fn at(text: &str, at: usize) -> Option<(&str, &'static str)> {
    let starts = text.char_indices().map(|(i, _)| i).filter(|&i| i <= at && at - i < 32);
    let mut best: Option<(&str, &'static str)> = None;
    for start in starts {
        let ends = text[start..].char_indices().skip(1).map(|(i, _)| start + i).chain(std::iter::once(text.len()));
        for end in ends.take_while(|&end| end - start <= 32) {
            if end <= at {
                continue;
            }
            let glyph = &text[start..end];
            if let Some(code) = shortcode(glyph)
                && best.is_none_or(|(b, _)| glyph.len() > b.len())
            {
                best = Some((glyph, code));
            }
        }
    }
    best
}

/// `:smile:` in plain text (a room preview) to its glyph; unknown codes stay.
pub fn replace_shortcodes(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(start) = rest.find(':') {
        out.push_str(&rest[..start]);
        let after = &rest[start + 1..];
        let end = after.find(':');
        let candidate = end
            .map(|e| &after[..e])
            .filter(|c| !c.is_empty() && c.chars().all(|ch| ch.is_ascii_alphanumeric() || "_+-".contains(ch)));
        match candidate.and_then(|c| unicode(c).map(|g| (c, g))) {
            Some((code, glyph)) => {
                out.push_str(glyph);
                rest = &after[code.len() + 1..];
            }
            None => {
                out.push(':');
                rest = after;
            }
        }
    }
    out.push_str(rest);
    out
}

/// The picker's base emojis of a category, in JoyPixels order.
pub fn category(name: &str) -> &'static [&'static str] {
    emojis().by_category.get(name).map(Vec::as_slice).unwrap_or(&[])
}

/// Shortcodes starting with `prefix`, shortest first, for `:` completion.
pub fn complete(prefix: &str, limit: usize) -> Vec<(&'static str, &'static str)> {
    let prefix = prefix.trim_start_matches(':').to_lowercase();
    if prefix.is_empty() {
        return Vec::new();
    }
    let mut hits: Vec<(&'static str, &'static str)> = emojis()
        .by_code
        .iter()
        .filter(|(code, _)| code.starts_with(&prefix))
        .map(|(code, glyph)| (*code, glyph.as_str()))
        .collect();
    hits.sort_by(|a, b| a.0.len().cmp(&b.0.len()).then(a.0.cmp(b.0)));
    hits.truncate(limit);
    hits
}

/// `emoji-custom.list`: each name and alias → the image's path on the server.
pub fn custom_index(response: &serde_json::Value) -> Vec<(String, String)> {
    use serde_json::Value;
    let list = response.pointer("/emojis/update").and_then(Value::as_array).cloned().unwrap_or_default();
    let mut index: Vec<(String, String)> = Vec::new();
    let valid: Vec<(String, String, Vec<String>)> = list
        .iter()
        .filter_map(|e| {
            let name = e.get("name")?.as_str()?.to_owned();
            let extension = e.get("extension")?.as_str()?.to_owned();
            let aliases = e
                .get("aliases")
                .and_then(Value::as_array)
                .map(|a| a.iter().filter_map(Value::as_str).map(str::to_owned).collect())
                .unwrap_or_default();
            Some((name, extension, aliases))
        })
        .collect();
    let path = |name: &str, ext: &str| {
        let encode = |s: &str| url::form_urlencoded::byte_serialize(s.as_bytes()).collect::<String>();
        format!("/emoji-custom/{}.{}", encode(name), encode(ext))
    };
    // Names first: an alias never hides another emoji's own name.
    for (name, ext, _) in &valid {
        if !index.iter().any(|(k, _)| k == name) {
            index.push((name.clone(), path(name, ext)));
        }
    }
    for (name, ext, aliases) in &valid {
        for alias in aliases {
            if !index.iter().any(|(k, _)| k == alias) {
                index.push((alias.clone(), path(name, ext)));
            }
        }
    }
    index
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn custom_emoji_index() {
        let index = custom_index(&serde_json::json!({"emojis":{"update":[
            {"name":"party_parrot","aliases":["parrot"],"extension":"gif"},
            {"name":"parrot","aliases":[],"extension":"png"},
            {"name":"broken"}
        ]}}));
        assert_eq!(
            index,
            [
                ("party_parrot".to_owned(), "/emoji-custom/party_parrot.gif".to_owned()),
                ("parrot".to_owned(), "/emoji-custom/parrot.png".to_owned())
            ]
        );
    }

    #[test]
    fn resolves_shortcodes() {
        assert_eq!(unicode("smile"), Some("😄"));
        assert_eq!(unicode(":+1:"), Some("👍"));
        assert_eq!(unicode("+1_tone3"), Some("👍🏽"));
        assert_eq!(unicode("flag_fr"), Some("🇫🇷"));
        assert_eq!(unicode("not_an_emoji"), None);
    }

    #[test]
    fn picker_categories_hold_base_emojis_only() {
        let people = category("people");
        assert!(people.contains(&"grinning"));
        assert!(!people.iter().any(|c| c.contains("_tone")));
        let total: usize = CATEGORIES.iter().map(|c| category(c).len()).sum();
        assert_eq!(total, 1918);
    }

    #[test]
    fn replaces_known_shortcodes_in_text() {
        assert_eq!(replace_shortcodes(":smile: :heart:"), "😄 ❤️");
        assert_eq!(replace_shortcodes("at 10:30: :party_parrot: ok :+1:"), "at 10:30: :party_parrot: ok 👍");
        assert_eq!(replace_shortcodes("no colons"), "no colons");
        assert_eq!(replace_shortcodes("trailing :"), "trailing :");
    }

    #[test]
    fn completes_by_prefix_shortest_first() {
        let hits = complete(":smi", 3);
        assert_eq!(hits[0].0, "smile");
        assert_eq!(hits.len(), 3);
        assert!(complete("", 5).is_empty());
    }

    #[test]
    fn glyphs_back_to_shortcodes() {
        assert_eq!(shortcode("😄"), Some("smile"));
        assert_eq!(shortcode("nope"), None);
        let text = "hi 👍🏽 and 🚀!";
        let thumb = text.find('👍').unwrap();
        assert_eq!(at(text, thumb).map(|(g, _)| g), Some("👍🏽"));
        assert_eq!(at(text, thumb + 4).map(|(g, _)| g), Some("👍🏽"));
        assert_eq!(at(text, text.find('🚀').unwrap()), Some(("🚀", "rocket")));
        assert_eq!(at(text, 0), None);
    }
}
