[package]
name = "rv-crypto-mobile"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[features]
bindgen = ["uniffi/cli"]

[lib]
name = "rv_crypto_mobile"
crate-type = ["lib", "cdylib"]

[[bin]]
name = "mobile-bindgen"
path = "src/bin/mobile-bindgen.rs"
required-features = ["bindgen"]

[dependencies]
rv-crypto = { path = "../rv-crypto" }
rv-protocol = { path = "../rv-protocol" }
getrandom = "0.4"
data-encoding = "2"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
sha2 = "0.11"
thiserror = "2"
uniffi = { version = "=0.32.2" }
url = "2.5.8"
zeroize = "1"

[dev-dependencies]
tempfile = "3"
rv-crypto-public = { path = "../rv-crypto-public" }
openmls = { version = "=0.9.0", default-features = false }
openmls_rust_crypto = "=0.6.0"
