/**
 * `babel-plugin-inline-import` lets `drizzle-orm/expo-sqlite/migrator`
 * import the `.sql` files generated by drizzle-kit as strings.
 */
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [['inline-import', { extensions: ['.sql'] }]],
  };
};
