/**
 * Emoji shortcode resolution.
 *
 * Rocket.Chat 8.5 pre-parses markdown into `msg.md` but **leaves the shortcode
 * intact**: `:smile:` becomes `{type:'EMOJI', shortCode:'smile'}`, with no
 * `unicode` field. The server only knows the name; it is up to the client to
 * know that `smile` is written 😄. Without this table, the screen shows `:smile:`.
 *
 * Corollary, and not a cosmetic one: the parser VALIDATES nothing. A lone
 * `:not_an_emoji:` comes out of the server as `BIG_EMOJI` like any real emoji.
 * The table is thus also the only judge of what is an emoji, and `null` means
 * "this is not one", not "I cannot display it". A server custom emoji
 * (`emoji-custom`) falls into this case: it stays a literal `:name:`, which
 * reads, rather than a missing glyph.
 *
 * Pure module, no React: testable under Node. The table itself is generated by
 * `scripts/generate-emojis.mjs` (see its doc for the source and the licence).
 */

import { EMOJI_CODES, EMOJIS_BY_CATEGORY } from './emojis.generated.ts';

let table: Record<string, string> | null = null;

/**
 * `null` if the shortcode is not a known emoji, never an empty string, which a
 * caller would mistake for "emoji without a glyph".
 */
export function unicodeOfShortcode(code: string): string | null {
  table ??= JSON.parse(EMOJI_CODES) as Record<string, string>;
  // `typeof` and not `in`: the `md` comes from others, and `:constructor:` is a
  // perfectly legal shortcode server-side. It would carry a function from
  // `Object`'s prototype all the way into a `<Text>`.
  const points = table[code];
  if (typeof points !== 'string') return null;
  // The table stores `1f9d1-1f3fb-200d-1f3a8`, not 🧑🏻‍🎨 (see the generator):
  // a single glyph would flip the whole string to UTF-16 in Hermes.
  // The generator guarantees the form; `lib/emojis.test.ts` checks it in bulk.
  return String.fromCodePoint(...points.split('-').map((p) => parseInt(p, 16)));
}

let codes: readonly string[] | null = null;

/**
 * All known standard shortcodes, for composer autocompletion
 * (`lib/emojiCompletion.ts`). Derived from the keys of the already parsed
 * table: a single `JSON.parse`, shared with `unicodeOfShortcode`. The list is
 * fixed (generated table), so it is cached, never copied on a keystroke.
 *
 * `readonly` and FROZEN: the same array is returned on each call. A future
 * caller sorting or truncating it in place would corrupt every later
 * completion; `Object.freeze` makes the mutation fail right away.
 */
export function codesEmojiStandard(): readonly string[] {
  table ??= JSON.parse(EMOJI_CODES) as Record<string, string>;
  return (codes ??= Object.freeze(Object.keys(table)));
}

/** The picker's eight categories, in canonical JoyPixels order. */
export type EmojiCategory =
  | 'people'
  | 'nature'
  | 'food'
  | 'activity'
  | 'travel'
  | 'objects'
  | 'symbols'
  | 'flags';

let categories: Record<EmojiCategory, readonly string[]> | null = null;

/**
 * The base codes grouped by category, for the emoji picker. Each list is
 * already ordered (JoyPixels order) and only holds codes resolvable by
 * `unicodeOfShortcode`. Parsed once, cached: the same object is returned on
 * each call, do not mutate it.
 */
export function emojisByCategory(): Record<EmojiCategory, readonly string[]> {
  return (categories ??= JSON.parse(EMOJIS_BY_CATEGORY) as Record<
    EmojiCategory,
    readonly string[]
  >);
}
