#!/usr/bin/env node
/**
 * Generates `lib/emojis.generated.ts`: the "shortcode -> Unicode character"
 * table that Rocket.Chat does NOT send.
 *
 *   npm run emojis:generate
 *
 * The server pre-parses `:smile:` into `{type:'EMOJI', shortCode:'smile'}` and
 * stops there (checked on 8.5, no `unicode` field comes with a shortcode).
 * Resolution belongs to the client, which therefore needs the table.
 *
 * Source: `emoji-toolkit` (JoyPixels), where Rocket.Chat gets its shortnames:
 * same source, same names, `:+1:` included. Its LICENSE.md clearly separates
 * the two regimes: **artwork** under the restrictive JoyPixels licence,
 * **"Javascript, JSON, PHP, CSS, HTML files" under MIT**. We only take the
 * JSON and ship no image: emojis are rendered by the system font (Noto Color
 * Emoji on Android). Hence a DEVELOPMENT dependency only, and this table
 * frozen in the repo: the runtime has nothing to install.
 *
 * Deterministic output (sorted keys, a single winner per collision): rerunning
 * the script on the same version must leave `git diff` empty.
 */
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUTPUT = join(ROOT, 'lib', 'emojis.generated.ts');

const emojis = require('emoji-toolkit/emoji.json');
const version = require('emoji-toolkit/package.json').version;

// Ascending `order`, so the winner of a shortcode collision does not depend
// on the JSON's key order.
const entries = Object.entries(emojis).sort((a, b) => (a[1].order ?? 0) - (b[1].order ?? 0));

const table = new Map();
let collisions = 0;
for (const [hex, e] of entries) {
  // `display: 0` = removed from the upstream picker (duplicates, obsolete codes).
  if (e.display !== 1) continue;
  // `fully_qualified` and not the key: `:heart:` is `2764-fe0f`, with the
  // variation selector. Without it, the font renders a black text ❤.
  const points = e.code_points?.fully_qualified || e.code_points?.base || hex;
  for (const name of [e.shortname, ...(e.shortname_alternates ?? [])]) {
    const code = name.slice(1, -1); // `:smile:` → `smile`
    if (table.has(code)) {
      if (table.get(code) !== points) collisions++;
      continue;
    }
    table.set(code, points);
  }
}

const sorted = [...table].sort((a, b) => (a[0] < b[0] ? -1 : 1));

// Escapes everything outside printable ASCII as `\uXXXX`, at the JSON level
// so `JSON.parse` restores it. This is not vanity:
//
//   Hermes stores each bytecode string as ASCII (1 B/char) or UTF-16
//   (2 B/char), and a SINGLE non-ASCII character switches the WHOLE string.
//
// The table with raw glyphs weighed 399,054 B in the release bundle (measured:
// +399,968 B); the 6222 ASCII keys paid double because of the emojis. In
// hexadecimal and without a single high byte (`piñata` included), it drops
// to 275,018 B. Decoding costs 236 ns per rendered emoji.
const toAscii = (obj) =>
  JSON.stringify(obj).replace(
    /[^\x20-\x7e]/g,
    (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, '0')}`,
  );

const json = toAscii(Object.fromEntries(sorted));
if (!/^[\x00-\x7f]*$/.test(json)) throw new Error('the table must stay pure ASCII');

// CATEGORY index for the emoji browser: base codes (no `_tone` skin variants,
// no `shortname_alternates`), grouped by category and ordered by `order`, the
// canonical JoyPixels order, the one the eye expects (grinning, smiley,
// smile...). The technical categories `regional` (letter tiles) and
// `modifier` (skin tone swatches) are left out: nobody picks those in a
// browser. Only a code really present in `table` is kept: same judge as the
// rendering, no unresolvable suggestion.
const CATEGORIES = [
  'people',
  'nature',
  'food',
  'activity',
  'travel',
  'objects',
  'symbols',
  'flags',
];
const byCategory = Object.fromEntries(CATEGORIES.map((cat) => [cat, []]));
const orderedBase = Object.values(emojis)
  .filter(
    (e) => e.display === 1 && CATEGORIES.includes(e.category) && !/_tone\d/.test(e.shortname),
  )
  .sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
for (const e of orderedBase) {
  const code = e.shortname.slice(1, -1);
  if (table.has(code)) byCategory[e.category].push(code);
}
const jsonCategories = toAscii(byCategory);
if (!/^[\x00-\x7f]*$/.test(jsonCategories)) throw new Error('the categories must stay pure ASCII');
const baseCount = Object.values(byCategory).reduce((n, l) => n + l.length, 0);

const file = `// ⚠️ GENERATED by \`npm run emojis:generate\`: do not edit by hand.
//
// ${table.size} Rocket.Chat shortcodes -> code points, extracted from
// emoji-toolkit ${version} (JoyPixels), whose JSON is MIT-licensed.
// No image is shipped: the system font renders the characters.
// See \`scripts/generate-emojis.mjs\` and \`lib/emojis.ts\`.
//
// A STRING, not an object literal: \`JSON.parse\` on first request costs
// less than ${table.size} properties materialised when the module loads,
// for a screen that sometimes shows no emoji at all.
//
// Hexadecimal CODE POINTS, not glyphs: the string stays ASCII, which
// Hermes stores at one byte per character instead of two (-124 KB).

export const EMOJI_CODES = ${JSON.stringify(json)};

// Emoji browser categories: ${baseCount} BASE codes (no skin tone
// variants), grouped and ordered like JoyPixels. A string \`JSON.parse\`d on
// demand, all ASCII, for the same reason as above. Only NAMES are stored
// (not the glyphs): rendering resolves them via \`unicodeOfShortcode\`.
export const EMOJIS_BY_CATEGORY = ${JSON.stringify(jsonCategories)};
`;

writeFileSync(OUTPUT, file);
const bytes = new TextEncoder().encode(file).length;
console.log(
  `lib/emojis.generated.ts: ${table.size} shortcodes + ${baseCount} sorted base codes, ${bytes} bytes ` +
    `(emoji-toolkit ${version}, ${collisions} diverging collision(s) dropped)`,
);
