// Generated by scripts/sync-crypto.mjs from ../mobile/providers/rocketvibe/cryptoRecovery.ts.
import type { CryptoAccount, CryptoRecoveryBridge } from "../bridge-types.ts";
import type { CryptoIdentityAccess } from "./cryptoIdentity.ts";
import type {
  PublishRootBackup,
  RootBackupReceipt,
  RootBackupSettlement,
  RootBackupState,
} from "../../protocol.ts";
import { decodeNative } from "./validation.ts";
import { NativeError } from "../transport.ts";
export type BackupStatus = {
  controls_root: boolean;
  root_fingerprint: string;
  receipt: RootBackupReceipt | null;
  pending: boolean;
  code_saved: boolean;
  cancel_requested: boolean;
};
export type BackupPreview = {
  id: string;
  root_fingerprint: string;
  backup_revision: string | null;
};
export type RestorePreview = {
  id: string;
  root_fingerprint: string;
  backup_id: string;
};
type Remote = {
  cryptoRootBackup: () => Promise<RootBackupState>;
  cryptoRootBackupOperation: (id: string) => Promise<RootBackupReceipt>;
  publishCryptoRootBackup: (
    request: PublishRootBackup,
  ) => Promise<RootBackupReceipt>;
  cancelCryptoRootBackup: (
    request: PublishRootBackup,
  ) => Promise<RootBackupSettlement>;
};
function fail(): never {
  throw new NativeError(0, "crypto_integrity_failed");
}
function record(value: unknown): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) fail();
  return value as Record<string, unknown>;
}
function fingerprint(value: unknown): string {
  if (typeof value !== "string" || !/^[0-9a-f]{64}$/.test(value)) fail();
  return value;
}
function id(value: unknown): string {
  if (typeof value !== "string" || !/^[0-9a-f]{32}$/.test(value)) fail();
  return value;
}
function status(value: unknown): BackupStatus {
  const r = record(value);
  if (
    typeof r.controls_root !== "boolean" ||
    typeof r.pending !== "boolean" ||
    typeof r.code_saved !== "boolean" ||
    typeof r.cancel_requested !== "boolean"
  )
    fail();
  return {
    controls_root: r.controls_root,
    root_fingerprint: fingerprint(r.root_fingerprint),
    receipt:
      r.receipt === null ? null : decodeNative("RootBackupReceipt", r.receipt),
    pending: r.pending,
    code_saved: r.code_saved,
    cancel_requested: r.cancel_requested,
  };
}
export class CryptoRecoveryAccess {
  private readonly identity: CryptoIdentityAccess;
  private readonly bridge: CryptoRecoveryBridge;
  private readonly remote: Remote;
  constructor(
    identity: CryptoIdentityAccess,
    bridge: CryptoRecoveryBridge,
    remote: Remote,
  ) {
    this.identity = identity;
    this.bridge = bridge;
    this.remote = remote;
  }
  private async action(
    handle: string,
    own: string,
    input: unknown,
    check: () => Promise<void>,
  ): Promise<unknown> {
    await check();
    const json = await this.bridge.recoveryAction(
      handle,
      own,
      JSON.stringify(input),
    );
    await check();
    if (typeof json !== "string" || json.length > 128 * 1024) fail();
    return JSON.parse(json) as unknown;
  }
  view(): Promise<BackupStatus> {
    return this.identity.withIdentity(async (handle, own, _read, check) =>
      status(await this.action(handle, own, { action: "view" }, check)),
    );
  }
  clearPreview(): Promise<void> {
    return this.identity.withIdentity(async (handle, own, _read, check) => {
      const r = record(
        await this.action(handle, own, { action: "clear_preview" }, check),
      );
      if (r.cleared !== true) fail();
    });
  }
  previewBackup(): Promise<BackupPreview> {
    return this.identity.withIdentity(async (handle, own, _read, check) => {
      await check();
      const remote = decodeNative(
        "RootBackupState",
        await this.remote.cryptoRootBackup(),
      );
      await check();
      const r = record(
        await this.action(
          handle,
          own,
          { action: "preview_backup", remote },
          check,
        ),
      );
      if (
        r.backup_revision !== null &&
        (typeof r.backup_revision !== "string" ||
          !/^[1-9][0-9]{0,18}$/.test(r.backup_revision) ||
          BigInt(r.backup_revision) > 9223372036854775807n)
      )
        fail();
      return {
        id: id(r.id),
        root_fingerprint: fingerprint(r.root_fingerprint),
        backup_revision: r.backup_revision,
      };
    });
  }
  prepareBackup(approval: string): Promise<BackupStatus> {
    return this.identity.withIdentity(async (handle, own, _read, check) =>
      status(
        await this.action(
          handle,
          own,
          { action: "prepare_backup", id: id(approval) },
          check,
        ),
      ),
    );
  }
  /** Explicit code view only. The caller clears this text on blur/account change. */
  code(): Promise<string> {
    return this.identity.withIdentity(async (handle, own, _read, check) => {
      const r = record(
        await this.action(handle, own, { action: "code" }, check),
      );
      if (
        typeof r.code !== "string" ||
        !/^rvk1-[0-9a-f]{64}-[0-9a-f]{8}$/.test(r.code)
      )
        fail();
      return r.code;
    });
  }
  private async resumeInner(
    handle: string,
    own: string,
    read: (user: string) => Promise<string>,
    check: () => Promise<void>,
    scope: CryptoAccount,
    known?: BackupStatus,
  ): Promise<BackupStatus> {
    const state =
      known ??
      status(await this.action(handle, own, { action: "view" }, check));
    const request = decodeNative(
      "PublishRootBackup",
      await this.action(
        handle,
        own,
        { action: state.cancel_requested ? "pending_cancel" : "pending" },
        check,
      ),
    );
    if (
      request.scope.instance_id !== scope.instance ||
      request.scope.data_epoch !== scope.dataEpoch
    )
      throw new NativeError(409, "crypto_scope_changed");
    await check();
    if (state.cancel_requested) {
      const result = decodeNative(
        "RootBackupSettlement",
        await this.remote.cancelCryptoRootBackup(request),
      );
      await check();
      return status(
        await this.action(
          handle,
          await read(scope.user),
          { action: "settle_cancel", result },
          check,
        ),
      );
    }
    let receipt: RootBackupReceipt;
    try {
      receipt = await this.remote.cryptoRootBackupOperation(
        request.operation_id,
      );
    } catch (error) {
      if (!(
        error instanceof NativeError &&
        error.status === 404 &&
        error.code === "not_found"
      ))
        throw error;
      await check();
      receipt = await this.remote.publishCryptoRootBackup(request);
    }
    await check();
    return status(
      await this.action(
        handle,
        await read(scope.user),
        {
          action: "acknowledge",
          receipt: decodeNative("RootBackupReceipt", receipt),
        },
        check,
      ),
    );
  }
  confirmSaved(): Promise<BackupStatus> {
    return this.identity.withIdentity(
      async (handle, own, read, check, scope) => {
        const saved = status(
          await this.action(handle, own, { action: "confirm_saved" }, check),
        );
        return this.resumeInner(handle, own, read, check, scope, saved);
      },
    );
  }
  resume(): Promise<BackupStatus> {
    return this.identity.withIdentity((handle, own, read, check, scope) =>
      this.resumeInner(handle, own, read, check, scope),
    );
  }
  cancel(): Promise<BackupStatus> {
    return this.identity.withIdentity(
      async (handle, own, read, check, scope) => {
        decodeNative(
          "PublishRootBackup",
          await this.action(handle, own, { action: "request_cancel" }, check),
        );
        return this.resumeInner(handle, own, read, check, scope);
      },
    );
  }
  previewRestore(code: string, expected: string): Promise<RestorePreview> {
    return this.identity.withIdentity(async (handle, own, _read, check) => {
      if (code.length !== 78)
        throw new NativeError(400, "crypto_recovery_failed");
      await check();
      const remote = decodeNative(
        "RootBackupState",
        await this.remote.cryptoRootBackup(),
      );
      await check();
      const r = record(
        await this.action(
          handle,
          own,
          {
            action: "preview_restore",
            remote,
            code,
            fingerprint: fingerprint(expected),
          },
          check,
        ),
      );
      if (r.root_fingerprint !== expected) fail();
      if (
        typeof r.backup_id !== "string" ||
        !/^[0-9a-f]{32}$/.test(r.backup_id)
      )
        fail();
      return {
        id: id(r.id),
        root_fingerprint: fingerprint(r.root_fingerprint),
        backup_id: r.backup_id,
      };
    });
  }
  restore(approval: string): Promise<void> {
    return this.identity.withIdentity(async (handle, own, _read, check) => {
      const r = record(
        await this.action(
          handle,
          own,
          { action: "restore", id: id(approval) },
          check,
        ),
      );
      if (r.restored !== true) fail();
    });
  }
}
