// Generated by scripts/sync-crypto.mjs from ../mobile/providers/rocketvibe/emojis.ts.
import { EMOJI_ALIASES_JSON } from "./emoji-aliases.generated.ts";

let aliases: Record<string, string> | null = null;
export function canonicalEmoji(input: string): string | null {
  if (input.length > 80) return null;
  const code =
    input.startsWith(":") && input.endsWith(":") ? input.slice(1, -1) : input;
  aliases ??= JSON.parse(EMOJI_ALIASES_JSON) as Record<string, string>;
  return Object.hasOwn(aliases, code) ? aliases[code] : null;
}
