// Real native HTTP transport, with an independent Node HS256 verifier.
import assert from 'node:assert/strict';
import {createHmac,timingSafeEqual} from 'node:crypto';
import {NativeTransport} from '../apps/mobile/fournisseurs/rocketvibe/transport.ts';
const env=process.env;
assert(env.RV_MEETINGS_SERVER && env.RV_MEETINGS_ROOM && env.RV_MEETINGS_PASSWORD && env.RV_MEETINGS_SECRET);
const c=new NativeTransport(env.RV_MEETINGS_SERVER);
const session=await c.login('meetings-owner',env.RV_MEETINGS_PASSWORD);
const discovery=await c.discover();
assert(discovery.capabilities.calls);
const room=env.RV_MEETINGS_ROOM;
const state=await c.roomReadState(room);
assert(state.membership_version);
const scope={membership_version:state.membership_version,data_epoch:discovery.data_epoch};
const input={...scope,operation_id:'typescript-meeting-operation'};
const meeting=await c.startMeeting(room,input);
assert.equal(meeting.room_id,room);
assert.equal(meeting.public_url.includes('?'),false);
assert.deepEqual(await c.startMeeting(room,input),meeting);
assert.deepEqual(await c.meeting(meeting.id),meeting);
const joined=await c.joinMeeting(meeting.id,scope);
const url=new URL(joined.url);
assert.equal(url.origin,'https://jitsi.example.test:8443');
assert.equal(url.origin+url.pathname,meeting.public_url);
assert.deepEqual([...url.searchParams.keys()],['jwt']);
const token=url.searchParams.get('jwt')!;
const parts=token.split('.');
assert.equal(parts.length,3);
assert.deepEqual(JSON.parse(Buffer.from(parts[0],'base64url').toString()),{alg:'HS256',typ:'JWT'});
const expected=createHmac('sha256',env.RV_MEETINGS_SECRET).update(parts.slice(0,2).join('.')).digest();
assert(timingSafeEqual(expected,Buffer.from(parts[2],'base64url')));
const claims=JSON.parse(Buffer.from(parts[1],'base64url').toString());
assert.equal(claims.iss,'rocketvibe');assert.equal(claims.aud,'jitsi');assert.equal(claims.sub,'jitsi.example.test');
assert.equal(claims.room,url.pathname.slice(1));assert.notEqual(claims.room,'*');
assert.equal(claims.context.user.name,'meetings-owner');
assert.equal(claims.context.user.id,session.user.id);
const now=Math.floor(Date.now()/1000);
assert(claims.exp>now && claims.exp<=now+120 && claims.exp-claims.iat<=120);
assert.equal(claims.exp,Math.floor(Date.parse(joined.expires_at)/1000));
const second=await c.joinMeeting(meeting.id,scope);
assert.notEqual(second.url,joined.url);
console.log('Mobile meeting transport and independent HS256 verification passed.');
