// Real native HTTP transport, with an independent Node HS256 verifier.
import assert from 'node:assert/strict';
import {createHmac,timingSafeEqual} from 'node:crypto';
import {mkdtempSync,unlinkSync,rmdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {NativeTransport} from '../apps/mobile/providers/rocketvibe/transport.ts';
import {NativeStore} from '../apps/mobile/providers/rocketvibe/store.ts';
import {nativeTestDatabase} from '../apps/mobile/providers/rocketvibe/testDatabase.ts';
import {createRocketVibeProvider} from '../apps/mobile/providers/rocketvibe/index.ts';
import {createWriteQueue} from '../apps/mobile/db/writeQueue.ts';
import {RestClient} from '../apps/mobile/lib/rest.ts';
import {mountProviderCalls} from '../apps/mobile/lib/providerCalls.ts';
import {memoizedCallAvailable,callContext,startConference,joinConference,probeCallAvailable} from '../apps/mobile/lib/call.ts';
const env=process.env;
assert(env.RV_MEETINGS_SERVER && env.RV_MEETINGS_ROOM && env.RV_MEETINGS_PASSWORD && env.RV_MEETINGS_SECRET);
const c=new NativeTransport(env.RV_MEETINGS_SERVER);
const session=await c.login('meetings-owner',env.RV_MEETINGS_PASSWORD);
const discovery=await c.discover();
assert(discovery.capabilities.calls);
const room=env.RV_MEETINGS_ROOM;
const state=await c.roomReadState(room);
assert(state.membership_version);
const scope={membership_version:state.membership_version,data_epoch:discovery.data_epoch};
const input={...scope,operation_id:'typescript-meeting-operation'};
const meeting=await c.startMeeting(room,input);
assert.equal(meeting.room_id,room);
assert.equal(meeting.public_url.includes('?'),false);
assert.deepEqual(await c.startMeeting(room,input),meeting);
assert.deepEqual(await c.meeting(meeting.id),meeting);
const joined=await c.joinMeeting(meeting.id,scope);
const url=new URL(joined.url);
assert.equal(url.origin,'https://jitsi.example.test:8443');
assert.equal(url.origin+url.pathname,meeting.public_url);
assert.deepEqual([...url.searchParams.keys()],['jwt']);
const token=url.searchParams.get('jwt')!;
const parts=token.split('.');
assert.equal(parts.length,3);
assert.deepEqual(JSON.parse(Buffer.from(parts[0],'base64url').toString()),{alg:'HS256',typ:'JWT'});
const expected=createHmac('sha256',env.RV_MEETINGS_SECRET).update(parts.slice(0,2).join('.')).digest();
assert(timingSafeEqual(expected,Buffer.from(parts[2],'base64url')));
const claims=JSON.parse(Buffer.from(parts[1],'base64url').toString());
assert.equal(claims.iss,'rocketvibe');assert.equal(claims.aud,'jitsi');assert.equal(claims.sub,'jitsi.example.test');
assert.equal(claims.room,url.pathname.slice(1));assert.notEqual(claims.room,'*');
assert.equal(claims.context.user.name,'meetings-owner');
assert.equal(claims.context.user.id,session.user.id);
const now=Math.floor(Date.now()/1000);
assert(claims.exp>now && claims.exp<=now+120 && claims.exp-claims.iat<=120);
assert.equal(claims.exp,Math.floor(Date.parse(joined.expires_at)/1000));
const second=await c.joinMeeting(meeting.id,scope);
assert.notEqual(second.url,joined.url);
// Same provider binding as ui/synchro.tsx, real account SQLite and HTTP journal.
const directory=mkdtempSync(join(tmpdir(),'rv-mobile-meeting-')),filename=join(directory,'account.sqlite');
const account={baseUrl:env.RV_MEETINGS_SERVER,authToken:session.token,userId:session.user.id,username:session.user.username,kind:'rocketvibe' as const,siteUrl:null,nativeInstanceId:discovery.instance_id,nativeDataEpoch:discovery.data_epoch};
const operations:string[]=[];
let loseAck=false,holdJoin=false,joinedRequest:()=>void=()=>{},releaseJoin:()=>void=()=>{};
const reader=new NativeTransport(account.baseUrl,async(input,options)=>{
  const path=new URL(String(input)).pathname;
  if(path.endsWith('/meetings')&&options?.method==='POST')operations.push(String(options.body));
  const response=await fetch(input,options);
  if(loseAck&&path.endsWith('/meetings')&&options?.method==='POST'&&response.ok){loseAck=false;await response.arrayBuffer();throw new TypeError('Lost meeting confirmation after server commit');}
  if(holdJoin&&path.endsWith('/join')&&response.ok){holdJoin=false;joinedRequest();await new Promise<void>(resolve=>{releaseJoin=resolve;});}
  return response;
});
reader.restore(session.token);
let harness=nativeTestDatabase(filename),store=new NativeStore(harness.adapter,createWriteQueue(),account),serial=0;
const client=new RestClient(account.baseUrl,{fetch:async()=>{throw new Error('Unexpected Rocket.Chat request');}});
let provider=createRocketVibeProvider(account,client,()=>`mobile-meeting-${++serial}`,store,{transport:reader});
let detach=mountProviderCalls(client,provider);
async function until(check:()=>boolean|Promise<boolean>){const deadline=Date.now()+15000;while(!await check()){assert(Date.now()<deadline,'Mobile meeting provider timed out');await new Promise(resolve=>setTimeout(resolve,25));}}
try{
  await provider.native!.chat.connect();assert(provider.native!.chat.status.online);
  assert(provider.capabilities.videoCall);assert(memoizedCallAvailable(client));
  const membership=(await store.readState(room))!.membership_version!;
  assert.equal(await probeCallAvailable(client,room,membership),true);
  assert.equal(await probeCallAvailable(client,room,'obsolete'),false);
  await until(()=>harness.db.prepare('SELECT call_id FROM messages WHERE call_id=?').get(meeting.id)?.call_id===meeting.id);
  const row=harness.db.prepare('SELECT system_type,call_id FROM messages WHERE call_id=?').get(meeting.id)!;
  assert.equal(row.system_type,'videoconf');
  loseAck=true;await assert.rejects(startConference(client,room,{membership}));
  const pending=harness.db.prepare('SELECT id,payload FROM native_meeting_intents').get()!;
  assert(pending.id);assert.equal(String(pending.payload).includes('jwt'),false);
  detach();provider.native!.chat.stop();await store.state();harness.db.close();
  harness=nativeTestDatabase(filename,false);store=new NativeStore(harness.adapter,createWriteQueue(),account);
  provider=createRocketVibeProvider(account,client,()=>`mobile-meeting-${++serial}`,store,{transport:reader});detach=mountProviderCalls(client,provider);
  await provider.native!.chat.connect();assert.equal(operations.length,1,'Reconnect must never launch an automatic call');
  const current=(await store.readState(room))!.membership_version!;
  const recovered=await startConference(client,room,{membership:current});assert.equal(recovered,meeting.id);
  assert.equal(operations.length,2);assert.equal(operations[0],operations[1]);
  assert.equal(harness.db.prepare('SELECT count(*) n FROM native_meeting_intents').get()?.n,0);
  const entered=await joinConference(client,meeting.id,{cam:false,mic:true},{room,membership:current});
  assert.equal(new URL(entered).origin,url.origin);assert.equal(new URL(entered).pathname,url.pathname);
  assert.equal(new URL(entered).hash,'#config.startWithVideoMuted=true&config.startWithAudioMuted=false');
  const shared=await provider.native!.chat.callLink(meeting.id,room,current);assert.equal(shared,meeting.public_url);assert.equal(shared.includes('jwt'),false);
  holdJoin=true;const arrived=new Promise<void>(resolve=>{joinedRequest=resolve;});
  const late=joinConference(client,meeting.id,undefined,{room,membership:current});await arrived;
  const before=callContext(client);detach();assert.notEqual(callContext(client),before);releaseJoin();
  await assert.rejects(late,/session_closed|call_scope_closed/);assert.equal(await probeCallAvailable(client,room,current),false);
  await assert.rejects(startConference(client,room),/call_provider_unavailable/);
  console.log('Mobile existing call helpers, native provider, real HTTP/WebSocket/SQLite, lost-confirmation restart, activity ID, private URL scope and independent HS256 verification passed.');
}finally{
  releaseJoin();detach();provider.native!.chat.stop();await store.state();harness.db.close();unlinkSync(filename);rmdirSync(directory);
}
