// Disposable PostgreSQL integration peer, using the actual mobile HTTP transport.
import assert from 'node:assert/strict';
import { NativeError, NativeTransport } from '../apps/mobile/fournisseurs/rocketvibe/transport.ts';
import type { RoomDetails, UpdateRoom } from '../apps/mobile/fournisseurs/rocketvibe/protocol.generated.ts';

const base=process.env.RV_ROOM_PEER_URL!;
const room=process.env.RV_ROOM_PEER_ROOM!;
const owner=new NativeTransport(base), peer=new NativeTransport(base);
const a=await owner.login('owner','room-test-password-2026');
const b=await peer.login('mobile-peer','room-test-password-2026');
const initial=await owner.roomDetails(room);
const settings=(details:RoomDetails):UpdateRoom=>({operation_id:'mobile-settings',expected_revision:details.revision,name:'Mobile metadata 🚀',private:true,topic:'Sujet mobile',description:'Description',announcement:'Annonce',read_only:false});
const update=settings(initial);
const changed=await owner.updateRoom(room,update);
assert.equal((await peer.roomDetails(room)).topic,update.topic);
await owner.changeRoomRole(room,b.user.id,{operation_id:'mobile-handover',expected_revision:changed.applied_revision,role:'owner'});
const demote={operation_id:'mobile-self-demote',expected_revision:(await owner.roomDetails(room)).revision,role:'member' as const};
const demoted=await owner.changeRoomRole(room,a.user.id,demote);
assert.equal((await owner.roomDetails(room)).permissions.role,'member');
assert.deepEqual(await owner.changeRoomRole(room,a.user.id,demote),demoted);
assert.deepEqual(await owner.updateRoom(room,update),changed);
const list=await peer.roomMembers(room);
assert.equal(list.members.filter(m=>m.role==='owner').length,1);
const leave={operation_id:'mobile-leave',expected_revision:list.revision};
const left=await owner.leaveRoom(room,leave);
assert.deepEqual(await owner.roomCommandReceipt(room,leave.operation_id),left);
assert.deepEqual(await owner.leaveRoom(room,leave),left);
await assert.rejects(owner.roomDetails(room),(e:unknown)=>e instanceof NativeError && e.code==='not_found');
await assert.rejects(peer.leaveRoom(room,{operation_id:'mobile-last-owner',expected_revision:(await peer.roomDetails(room)).revision}),(e:unknown)=>e instanceof NativeError && e.code==='last_room_owner');
console.log(JSON.stringify({metadata:true,handover:true,selfDemotion:true,receiptAfterLeave:true,lastOwnerProtected:true}));
