[workspace]
resolver = "3"
members = ["crates/rv-core", "crates/rv-ffi", "crates/rv-gtk", "crates/rv-native"]

[workspace.package]
edition = "2024"
version = "0.6.0"
license = "MIT"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
result_large_err = "allow"
